project_id = "gypznlmfkarzgzfbqhks"

[functions.create-stripe-checkout]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.delete-account]
verify_jwt = false
